### ISSUE TITLE
from model.ResNet18 import ResNet18_pure

### ISSUE THREAD

**Issue by jacksonwu09** [wm-Githuber/AFCF3D-Net#3]
这里的ResNet18_pure代码是要进行什么修改

**Comment by wm-Githuber** [comment]
> 这里的ResNet18_pure代码是要进行什么修改

之前调用2D的ResNet，后面就没用了

**Comment by jacksonwu09** [comment]
我看model那个块中也没写resnet.py，那注释掉不会影响吧
<img width="137" alt="屏幕截图 2024-03-22 181319" src="https://github.com/wm-Githuber/AFCF3D-Net/assets/69404310/dc02778a-ee39-4614-97c9-e5f392acda1f">
还有这块的txt是自己弄成下面这样吗
<img width="84" alt="image" src="https://github.com/wm-Githuber/AFCF3D-Net/assets/69404310/395ca32b-2bf8-4a03-b315-e5590be247e2">
就是数据集那其实结构您可以优化下，感觉不是很清晰，就是train、test、val图片的位置不太明确

**Comment by wm-Githuber** [comment]
不会，直接更改加载数据集路径就可以运行。好的，谢谢您的建议



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月22日 18:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wm-Githuber/AFCF3D-Net] from model.ResNet18 import ResNet18_pure (Issue #3) |

我看model那个块中也没写resnet.py，那注释掉不会影响吧
2024-03-22.181319.png (view on web)
还有这块的txt是自己弄成下面这样吗
image.png (view on web)
就是数据集那其实结构您可以优化下，感觉不是很清晰，就是train、test、val图片的位置不太明确

**Comment by wm-Githuber** [comment]
是的，根据自己的数据情况，单独把这些数据名称放进一个txt中



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月22日 18:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wm-Githuber/AFCF3D-Net] from model.ResNet18 import ResNet18_pure (Issue #3) |

我看model那个块中也没写resnet.py，那注释掉不会影响吧
2024-03-22.181319.png (view on web)
还有这块的txt是自己弄成下面这样吗
image.png (view on web)
就是数据集那其实结构您可以优化下，感觉不是很清晰，就是train、test、val图片的位置不太明确

**Comment by jacksonwu09** [comment]
好的，谢谢

**Comment by jacksonwu09** [comment]
您是在什么配置下跑的，我在4090上单卡跑，24g显存也爆了，batch_size调成4都不行，您是多卡跑的吗

**Comment by wm-Githuber** [comment]
3080ti，我实验的时候没问题，bs是8，你看看是不是你gpu加载成功没



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月22日 19:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wm-Githuber/AFCF3D-Net] from model.ResNet18 import ResNet18_pure (Issue #3) |

您是在什么配置下跑的，我在4090上单卡跑，24g显存也爆了，batch_size调成1都不行，您是多卡跑的吗

**Comment by jacksonwu09** [comment]
gpu应该是加载的了，我租了好几台设备试，一直爆显存，后面然后把bs调成2才能跑

**Comment by wm-Githuber** [comment]
这个不应该，我用我的电脑和我师弟的电脑都测试过，用的都是8



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月22日 21:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wm-Githuber/AFCF3D-Net] from model.ResNet18 import ResNet18_pure (Issue #3) |

gpu应该是加载的了，我租了好几台设备试，一直爆显存，后面然后把bs调成2才能跑

**Comment by jacksonwu09** [comment]
好的，我自己再试试看

**Comment by jacksonwu09** [comment]
<img width="981" alt="image" src="https://github.com/wm-Githuber/AFCF3D-Net/assets/69404310/7b5c5986-d6fa-4cac-9768-0572a6760ed6">
<img width="409" alt="屏幕截图 2024-03-23 184543" src="https://github.com/wm-Githuber/AFCF3D-Net/assets/69404310/226b4f29-0749-494b-9646-4d18c5637c10">
还是不行，gpu明显加载了呀，那个显存都直接满了

**Comment by wm-Githuber** [comment]
你的影像大小是256的吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月23日 18:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wm-Githuber/AFCF3D-Net] from model.ResNet18 import ResNet18_pure (Issue #3) |

image.png (view on web)2024-03-23.184543.png (view on web) 还是不行，gpu明显加载了呀，那个显存都直接满了

**Comment by jacksonwu09** [comment]
我用的是LEVIR数据集，我把imagesize换成1024也不行

**Comment by wm-Githuber** [comment]
我用LEVIR是裁剪成256x256的大小，我重新测试了下，BS设置成8是没有问题的，你再看下你是不是哪里没调对
![image](https://github.com/wm-Githuber/AFCF3D-Net/assets/66511993/55878d91-508f-4a0c-a08b-ef1c822d4126)

**Comment by jacksonwu09** [comment]
你是人为的进行了数据的裁剪吗

**Comment by wm-Githuber** [comment]
是的，把原始的一个1024裁剪成多个256

**Comment by jacksonwu09** [comment]
可以了，谢谢您

**Comment by jacksonwu09** [comment]
我想问一下，我就训练了20epoch
然后进行test
出现如下的报错：
<img width="927" alt="image" src="https://github.com/wm-Githuber/AFCF3D-Net/assets/69404310/3b286317-9424-4bdb-8dca-f28492dc9911">
我想请问下这什么原因，您遇过吗，或者说你可以说说除了要改模型的位置、测试数据集的位置还有哪些位置需要进行修改

**Comment by wm-Githuber** [comment]
你是在Ubantu系统上测试的吗，看这个错误应该是你保存模型和读取模型不一致导致的，我在windows上没有报这个错误，我看你的截图是Ubantu系统，你搜一下是不是这两个系统模型保存和读取是不是不太一致导致的

**Comment by jacksonwu09** [comment]
不是系统的问题，是你的train.py和test.py加载的model不是一个我没注意看这个细节，修正后，是可以进行测试的

**Comment by jacksonwu09** [comment]
<img width="335" alt="image" src="https://github.com/wm-Githuber/AFCF3D-Net/assets/69404310/04cfbc44-03d5-491f-a8dc-4f5f6aa8b9c5">
你好，我想问下，为什么在进行test时，生成的4000张图片全是黑的，没有生成差异图吗

**Comment by wm-Githuber** [comment]
你把图片转到0-255试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月30日 22:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wm-Githuber/AFCF3D-Net] from model.ResNet18 import ResNet18_pure (Issue #3) |

image.png (view on web) 你好，我想问下，为什么在进行test时，生成的4000张图片全是黑的，没有生成差异图吗
